name: PushNotificationConfig
platforms:
  - blackberry


properties:
  - name: types
    platforms:
      - blackberry
  - name: success
    platforms:
      - blackberry
  - name: error
    platforms:
      - blackberry
  - name: callback
    platforms:
      - blackberry
